USE `gamabank`;

/*Data for the table `accountoperation` */

insert  into `accountoperation`(`accountOperationCod`,`accountOperationName`,`accountOperationStatus`) values 
(1,'Transfer','Active'),
(2,'Withdraw','Active'),
(3,'Deposit','Active'),
(4,'Payment','Active');

/*Data for the table `bank` */

insert  into `bank`(`bankCode`,`bankName`,`bankStatus`) values 
(0,'BMF Bovespa S.A. – Bolsa de Valores, Mercadorias e Futuros – Camara BMFBOVESPA','Active'),
(1,'Banco Do Brasil S.A (BB)','Active'),
(3,'Banco Da Amazônia S.A.','Active'),
(4,'Banco Do Nordeste Do Brasil S.A.','Active'),
(7,'BNDES (Banco Nacional Do Desenvolvimento Social)','Active'),
(10,'CREDICOAMO CRÉDITO RURAL COOPERATIVA','Active'),
(11,'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)','Active'),
(12,'Banco Inbursa','Active'),
(14,'STATE STREET BRASIL S.A. – BANCO COMERCIAL','Active'),
(15,'UBS Brasil Cctvm S.A.','Active'),
(16,'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI','Active'),
(17,'Bny Mellon Banco S.A.','Active'),
(18,'Banco Tricury S.A.','Active'),
(21,'Banco Banestes S.A.','Active'),
(24,'Banco Bandepe S.A.','Active'),
(25,'Banco Alfa S.A.','Active'),
(29,'Banco Itaú Consignado S.A.','Active'),
(33,'Banco Santander Brasil S.A.','Active'),
(36,'Banco Bradesco BBI S.A.','Active'),
(37,'Banco Do Estado Do Pará S.A.','Active'),
(40,'Banco Cargill S.A.','Active'),
(41,'Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A.','Active'),
(47,'Banco do Estado de Sergipe S.A.','Active'),
(60,'Confidence Cc S.A.','Active'),
(62,'Hipercard Banco Múltiplo S.A.','Active'),
(63,'Banco Bradescard','Active'),
(64,'Goldman Sachs Do Brasil Bm S.A.','Active'),
(65,'Banco Andbank S.A.','Active'),
(66,'Banco Morgan Stanley S.A.','Active'),
(69,'Banco Crefisa S.A.','Active'),
(70,'BRB – Banco De Brasília S.A.','Active'),
(74,'Banco J. Safra S.A.','Active'),
(75,'Bco Abn Amro S.A.','Active'),
(76,'Banco KDB Brasil S.A.','Active'),
(77,'Banco Inter S.A.','Active'),
(78,'Haitong Bi Do Brasil S.A.','Active'),
(79,'Banco Original Do Agronegócio S.A.','Active'),
(80,'B&T Cc Ltda','Active'),
(81,'Banco Seguro S.A.','Active'),
(82,'Banco Topázio S.A.','Active'),
(83,'Banco Da China Brasil S.A.','Active'),
(84,'UNIPRIME NORTE DO PARANÁ – COOPERATIVA DE CRÉDITO LTDA','Active'),
(85,'Cooperativa Central de Créditos – Ailos','Active'),
(88,'BANCO RANDON S.A.','Active'),
(89,'CREDISAN COOPERATIVA DE CRÉDITO','Active'),
(91,'Central De Cooperativas De Economia E Crédito Mútuo Do Estado Do Rio Grande Do S','Active'),
(92,'BRK S.A.','Active'),
(93,'PóloCred Scmepp Ltda','Active'),
(94,'Banco Finaxis','Active'),
(95,'Travelex Banco de Câmbio S.A.','Active'),
(96,'Banco B3 S.A.','Active'),
(97,'Credisis – Central de Cooperativas de Crédito Ltda.','Active'),
(98,'Credialiança Ccr','Active'),
(99,'Uniprime Central Ccc Ltda','Active'),
(100,'Planner Corretora De Valores S.A.','Active'),
(101,'Renascença Dtvm Ltda','Active'),
(102,'XP Investimentos S.A.','Active'),
(104,'Caixa Econômica Federal (CEF)','Active'),
(105,'Lecca Cfi S.A.','Active'),
(107,'Banco Bocom BBM S.A.','Active'),
(108,'Portocred S.A.','Active'),
(111,'Banco Oliveira Trust Dtvm S.A.','Active'),
(113,'Magliano S.A.','Active'),
(114,'Central Cooperativa De Crédito no Estado do Espírito Santo','Active'),
(117,'Advanced Cc Ltda','Active'),
(118,'Standard Chartered Bi S.A.','Active'),
(119,'Banco Western Union do Brasil S.A.','Active'),
(120,'Banco Rodobens S.A.','Active'),
(121,'Banco Agibank S.A.','Active'),
(122,'Banco Bradesco BERJ S.A.','Active'),
(124,'Banco Woori Bank Do Brasil S.A.','Active'),
(125,'Brasil Plural S.A Banco','Active'),
(126,'BR Partners Banco de Investimento S.A.','Active'),
(127,'Codepe Cvc S.A.','Active'),
(128,'Ms Bank S.A Banco De Câmbio','Active'),
(129,'UBS Brasil Bi S.A.','Active'),
(130,'Caruana Scfi','Active'),
(131,'Tullett Prebon Brasil Cvc Ltda','Active'),
(132,'ICBC do Brasil Bm S.A.','Active'),
(133,'Cresol Confederação','Active'),
(134,'BGC Liquidez Dtvm Ltda','Active'),
(136,'Unicred Cooperativa LTDA','Active'),
(137,'Multimoney Cc Ltda','Active'),
(138,'Get Money Cc Ltda','Active'),
(139,'Intesa Sanpaolo Brasil S.A.','Active'),
(140,'Easynvest – Título Cv S.A.','Active'),
(142,'Broker Brasil Cc Ltda','Active'),
(143,'Treviso Cc S.A.','Active'),
(144,'Bexs Banco De Cambio S.A.','Active'),
(145,'Levycam Ccv Ltda','Active'),
(146,'Guitta Cc Ltda','Active'),
(149,'Facta S.A. Cfi','Active'),
(157,'Icap Do Brasil Ctvm Ltda','Active'),
(159,'Casa do Crédito S.A.','Active'),
(163,'Commerzbank Brasil S.A Banco Múltiplo','Active'),
(169,'Banco Olé Bonsucesso Consignado S.A.','Active'),
(172,'Albatross Ccv S.A.','Active'),
(173,'BRL Trust Dtvm Sa','Active'),
(174,'PEFISA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO','Active'),
(177,'Guide Investimentos S.A. Corretora de Valores','Active'),
(180,'Cm Capital Markets Cctvm Ltda','Active'),
(182,'Dacasa Financeira S/A','Active'),
(183,'Socred S.A.','Active'),
(184,'Banco Itaú BBA S.A.','Active'),
(188,'Ativa S.A Investimentos','Active'),
(189,'Hs Financeira','Active'),
(190,'Servicoop','Active'),
(191,'Nova Futura Ctvm Ltda','Active'),
(194,'Parmetal Dtvm Ltda','Active'),
(196,'Banco Fair Cc S.A.','Active'),
(197,'Stone Pagamentos S.A.','Active'),
(204,'Banco Bradesco Cartoes S.A.','Active'),
(208,'Banco BTG Pactual S.A.','Active'),
(212,'Banco Original S.A.','Active'),
(213,'Bco Arbi S.A.','Active'),
(217,'Banco John Deere S.A.','Active'),
(218,'Banco Bs2 S.A.','Active'),
(222,'Banco Crédit Agricole Br S.A.','Active'),
(224,'Banco Fibra S.A.','Active'),
(233,'Banco Cifra S.A.','Active'),
(237,'Next Bank (Mesmo Código Do Bradesco)','Active'),
(241,'Banco Classico S.A.','Active'),
(243,'Banco Máxima S.A.','Active'),
(246,'Banco Abc Brasil S.A.','Active'),
(249,'Banco Investcred Unibanco S.A.','Active'),
(250,'Banco Bcv','Active'),
(253,'Bexs Cc S.A.','Active'),
(254,'Paraná Banco S.A.','Active'),
(259,'MONEYCORP BANCO DE CÂMBIO S.A.','Active'),
(260,'Nu Pagamentos S.A (Nubank)','Active'),
(265,'Banco Fator S.A.','Active'),
(266,'Banco Cedula S.A.','Active'),
(268,'Barigui Companhia Hipotecária','Active'),
(269,'Hsbc Banco De Investimento','Active'),
(270,'Sagitur Cc Ltda','Active'),
(271,'Ib Cctvm Ltda','Active'),
(272,'AGK Corretora de Câmbio S.A.','Active'),
(273,'Ccr De São Miguel Do Oeste','Active'),
(274,'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT','Active'),
(276,'Senff S.A.','Active'),
(278,'Genial Investimentos Cvm S.A.','Active'),
(279,'Ccr De Primavera Do Leste','Active'),
(280,'Avista S.A.','Active'),
(281,'Cooperativa de Crédito Rural Coopavel','Active'),
(283,'RB Capital Investimentos Dtvm Ltda','Active'),
(285,'Frente Cc Ltda','Active'),
(286,'Cooperativa de Crédito Rural de De Ouro','Active'),
(288,'Carol Dtvm Ltda','Active'),
(289,'DECYSEO CORRETORA DE CAMBIO LTDA.','Active'),
(290,'PagSeguro Internet S.A.','Active'),
(292,'BS2 Distribuidora De Títulos E Investimentos','Active'),
(293,'Lastro Rdv Dtvm Ltda','Active'),
(296,'VISION S.A. CORRETORA DE CAMBIO','Active'),
(298,'Vip’s Cc Ltda','Active'),
(299,'SOROCRED   CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.','Active'),
(300,'Banco La Nacion Argentina','Active'),
(301,'BPP Instituição De Pagamentos S.A.','Active'),
(306,'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.','Active'),
(307,'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.','Active'),
(309,'CAMBIONET CORRETORA DE CÂMBIO LTDA.','Active'),
(310,'VORTX Dtvm Ltda','Active'),
(313,'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.','Active'),
(315,'PI Distribuidora de Títulos e Valores Mobiliários S.A.','Active'),
(318,'Banco BMG S.A.','Active'),
(319,'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA','Active'),
(320,'China Construction Bank – Ccb Brasil S.A.','Active'),
(321,'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT','Active'),
(322,'Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz','Active'),
(323,'Mercado Pago – Conta Do Mercado Livre','Active'),
(324,'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(325,'Órama Distribuidora de Títulos e Valores Mobiliários S.A.','Active'),
(326,'PARATI – CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.','Active'),
(329,'QI Sociedade de Crédito Direto S.A.','Active'),
(330,'Banco Bari de Investimentos e Financiamentos S.A.','Active'),
(331,'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.','Active'),
(332,'Acesso Soluções de Pagamento S.A.','Active'),
(335,'Banco Digio S.A.','Active'),
(336,'Banco C6 S.A – C6 Bank','Active'),
(340,'Super Pagamentos S/A (Superdital)','Active'),
(341,'Itaú Unibanco S.A.','Active'),
(342,'Creditas Sociedade de Crédito Direto S.A.','Active'),
(343,'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.','Active'),
(348,'Banco XP S/A','Active'),
(349,'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO','Active'),
(350,'Cooperativa De Crédito Rural De Pequenos Agricultores E Da Reforma Agrária Do Ce','Active'),
(352,'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA','Active'),
(354,'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES','Active'),
(355,'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(359,'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A','Active'),
(360,'TRINUS Capital Distribuidora De Títulos E Valores Mobiliários S.A.','Active'),
(362,'CIELO S.A.','Active'),
(363,'SOCOPA SOCIEDADE CORRETORA PAULISTA S.A.','Active'),
(364,'GERENCIANET S.A.','Active'),
(365,'SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS','Active'),
(366,'Banco Societe Generale Brasil','Active'),
(367,'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.','Active'),
(368,'Banco CSF S.A.','Active'),
(370,'Banco Mizuho S.A.','Active'),
(371,'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.','Active'),
(373,'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.','Active'),
(374,'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.','Active'),
(376,'Banco J.P. Morgan S.A.','Active'),
(377,'MS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA','Active'),
(378,'BBC LEASING S.A. – Arrendamento Mercantil','Active'),
(379,'COOPERFORTE – Cooperativa De Economia E Crédito Mútuo Dos Funcionários De Instit','Active'),
(380,'PICPAY SERVICOS S.A.','Active'),
(381,'BANCO MERCEDES-BENZ DO BRASIL S.A.','Active'),
(382,'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L','Active'),
(383,'BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA.','Active'),
(384,'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO','Active'),
(387,'Banco Toyota do Brasil S.A.','Active'),
(389,'Banco Mercantil Do Brasil S.A.','Active'),
(390,'BANCO GM S.A.','Active'),
(391,'COOPERATIVA DE CRÉDITO RURAL DE IBIAM – SULCREDI/IBIAM','Active'),
(393,'Banco Volkswagen S.A.','Active'),
(394,'Banco Bradesco Financiamentos S.A.','Active'),
(396,'HUB PAGAMENTOS S.A.','Active'),
(397,'LISTO SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(399,'Kirton Bank S.A. – Banco Múltiplo','Active'),
(403,'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(404,'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(408,'BÔNUSCRED SOCIEDADE DE CRÉDITO DIRETO S.A.','Active'),
(412,'Banco Capital S.A.','Active'),
(422,'Banco Safra S.A.','Active'),
(456,'Banco MUFG Brasil S.A.','Active'),
(464,'Banco Sumitomo Mitsui Brasil S.A.','Active'),
(473,'Banco Caixa Geral Brasil S.A.','Active'),
(477,'Citibank N.A.','Active'),
(479,'Banco ItauBank S.A.','Active'),
(487,'Deutsche Bank S.A (Banco Alemão)','Active'),
(488,'Jpmorgan Chase Bank','Active'),
(492,'Ing Bank N.V.','Active'),
(494,'Banco Rep Oriental Uruguay','Active'),
(495,'La Provincia Buenos Aires Banco','Active'),
(505,'Banco Credit Suisse (Brl) S.A.','Active'),
(545,'Senso Ccvm S.A.','Active'),
(600,'Banco Luso Brasileiro S.A.','Active'),
(604,'Banco Industrial Do Brasil S.A.','Active'),
(610,'Banco VR S.A.','Active'),
(611,'Banco Paulista','Active'),
(612,'Banco Guanabara S.A.','Active'),
(613,'Omni Banco S.A.','Active'),
(623,'Banco Pan S.A.','Active'),
(626,'BANCO C6 CONSIGNADO S.A.','Active'),
(630,'Banco Smartbank S.A.','Active'),
(633,'Banco Rendimento S.A.','Active'),
(634,'Banco Triangulo S.A (Banco Triângulo)','Active'),
(637,'Banco Sofisa S.A (Sofisa Direto)','Active'),
(641,'Banco Alvorada S.A.','Active'),
(643,'Banco Pine S.A.','Active'),
(652,'Itaú Unibanco Holding Bm S.A.','Active'),
(653,'Banco Indusval S.A.','Active'),
(654,'BANCO DIGIMAIS S.A.','Active'),
(655,'Neon Pagamentos S.A (Memso Código Do Banco Votorantim)','Active'),
(707,'Banco Daycoval S.A.','Active'),
(712,'Banco Ourinvest S.A.','Active'),
(739,'Banco Cetelem S.A.','Active'),
(741,'Banco Ribeirão Preto S.A.','Active'),
(743,'Banco Semear S.A.','Active'),
(745,'Banco Citibank S.A.','Active'),
(746,'Banco Modal S.A.','Active'),
(747,'Banco Rabobank Internacional Do Brasil S.A.','Active'),
(748,'Banco Cooperativa Sicredi S.A.','Active'),
(751,'Scotiabank Brasil','Active'),
(752,'Banco BNP Paribas Brasil S.A.','Active'),
(753,'Novo Banco Continental S.A Bm','Active'),
(754,'Banco Sistema S.A.','Active'),
(755,'Bank of America Merrill Lynch Banco Múltiplo S.A.','Active'),
(756,'Bancoob – Banco Cooperativo Do Brasil S.A.','Active'),
(757,'Banco Keb Hana Do Brasil S.A.','Active'),
(999,'GamaBank','Active');

