### Verify
POST http://localhost:3001/user/deposit HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGVuaW5oYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE2MTU3Mzg3NjYsImV4cCI6MTYxNTczODg4Nn0.LU0j9GQBFGIuPEflnNkZGFpdGXO9XVLsjcfTr5wvP_g


{
    "name": "Bernardo",
    "CPF": "153.770.217-38"
}