### SIGNUP
POST http://localhost:3001/auth/signup HTTP/1.1
Content-Type: application/json

{
    "clientEmail": "heleninhaaaa@gmail.com",
    "clientPassword": "B3rn@rdo",
    "clientName": "Lenão Hurricane",
    "clientCPF" : "37586157049"
}
