POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZ2FtYUBnYW1hLmNvbSIsImlhdCI6MTYxNjAwNjgzMiwiZXhwIjoxNjE2ODcwODMyfQ.W1-OmxJwHlSGTCNuhvigHDMD0LFzvm3kBj6gb4c7uUo

{
    "accAnother": 2,
    "value": 17,
    "CPF": "83628906067"
}

###
POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json


{
    "account": 1,
    "bank": 4,
    "accAnother": 105,
    "value": 10000,
    "CPF": "06889461002"
}

