POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHJlYWJyaXR0b0BnYW1hYmFuay5jb20iLCJpYXQiOjE2MTU5MTIyNzcsImV4cCI6MTYxNjc3NjI3N30.MBT5IUxgrrQEy8lcoKVXjIOI3Lb5qCIjOYOCq-S7zdU

{
    "accAnother": 2,
    "value": 10.5,
    "CPF": "83628906067"
}

###
POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json


{
    "account": 1,
    "bank": 4,
    "accAnother": 105,
    "value": 10000,
    "CPF": "06889461002"
}

