-- MySQL Script generated by MySQL Workbench
-- Sat Apr  3 13:17:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamabank_test
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamabank_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamabank_test` DEFAULT CHARACTER SET latin1;
USE `gamabank_test`;
-- -----------------------------------------------------
-- Table `gamabank_test`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `salt` VARCHAR(100) NULL DEFAULT NULL,
  `criado_em` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `senha` (`senha` ASC)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
-- -----------------------------------------------------
-- Table `gamabank_test`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`conta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `saldo` DOUBLE NULL DEFAULT NULL,
  `dateAbertura` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario` (`idUsuario` ASC),
  CONSTRAINT `conta_ibfk_1` FOREIGN KEY (`idUsuario`) REFERENCES `gamabank_test`.`usuario` (`id`)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
-- -----------------------------------------------------
-- Table `gamabank_test`.`credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`credito` (
  `idConta` INT(11) NOT NULL,
  `limite` DOUBLE NULL DEFAULT NULL,
  `limiteDisponivel` DOUBLE NULL DEFAULT NULL,
  INDEX `idConta` (`idConta` ASC),
  CONSTRAINT `credito_ibfk_1` FOREIGN KEY (`idConta`) REFERENCES `gamabank_test`.`conta` (`id`)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
-- -----------------------------------------------------
-- Table `gamabank_test`.`fatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`fatura` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idConta` INT(11) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `diaFechamento` INT(11) NOT NULL,
  `diaVencimento` INT(11) NOT NULL,
  `mesReferencia` VARCHAR(7) NOT NULL,
  `valorConsolidado` DOUBLE NULL DEFAULT NULL,
  `valorPago` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idConta` (`idConta` ASC),
  CONSTRAINT `fatura_ibfk_1` FOREIGN KEY (`idConta`) REFERENCES `gamabank_test`.`conta` (`id`)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
-- -----------------------------------------------------
-- Table `gamabank_test`.`lancamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`lancamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idConta` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idConta` (`idConta` ASC),
  CONSTRAINT `lancamentos_ibfk_1` FOREIGN KEY (`idConta`) REFERENCES `gamabank_test`.`conta` (`id`)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
-- -----------------------------------------------------
-- Table `gamabank_test`.`transacoescredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamabank_test`.`transacoescredito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `idFatura` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idFatura` (`idFatura` ASC),
  CONSTRAINT `transacoescredito_ibfk_1` FOREIGN KEY (`idFatura`) REFERENCES `gamabank_test`.`fatura` (`id`)
) ENGINE = Memory DEFAULT CHARACTER SET = latin1;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;