-- MySQL Script generated by MySQL Workbench
-- Sat Apr  3 13:17:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetoacceture
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoacceture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoacceture` DEFAULT CHARACTER SET latin1 ;
USE `projetoacceture` ;

-- -----------------------------------------------------
-- Table `projetoacceture`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`usuarios` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `senha` (`senha` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoacceture`.`contacorrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`contacorrente` (
  `id` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  `saldo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario` (`idUsuario` ASC),
  CONSTRAINT `contacorrente_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `projetoacceture`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoacceture`.`credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`credito` (
  `idContaCorrente` INT(11) NOT NULL,
  `limite` DOUBLE NULL DEFAULT NULL,
  `limiteDisponivel` DOUBLE NULL DEFAULT NULL,
  INDEX `idContaCorrente` (`idContaCorrente` ASC),
  CONSTRAINT `credito_ibfk_1`
    FOREIGN KEY (`idContaCorrente`)
    REFERENCES `projetoacceture`.`contacorrente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoacceture`.`fatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`fatura` (
  `id` INT(11) NOT NULL,
  `idContaCorrente` INT(11) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `diaFechamento` INT(11) NOT NULL,
  `mesReferencia` DATE NOT NULL,
  `valorConsolidado` DOUBLE NULL DEFAULT NULL,
  `valorPago` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idContaCorrente` (`idContaCorrente` ASC),
  CONSTRAINT `fatura_ibfk_1`
    FOREIGN KEY (`idContaCorrente`)
    REFERENCES `projetoacceture`.`contacorrente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoacceture`.`lancamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`lancamentos` (
  `id` INT(11) NOT NULL,
  `idContaCorrente` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idContaCorrente` (`idContaCorrente` ASC),
  CONSTRAINT `lancamentos_ibfk_1`
    FOREIGN KEY (`idContaCorrente`)
    REFERENCES `projetoacceture`.`contacorrente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoacceture`.`transacoescredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoacceture`.`transacoescredito` (
  `id` INT(11) NOT NULL,
  `idFatura` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idFatura` (`idFatura` ASC),
  CONSTRAINT `transacoescredito_ibfk_1`
    FOREIGN KEY (`idFatura`)
    REFERENCES `projetoacceture`.`fatura` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
